version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html/CodeDeployGitHubDemo
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  Install:
    
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

